<a href="https://colab.research.google.com/github/umanggupta598/umang-codes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mixed_list = [[2, 3, 1], 'New York', 5.6, -10, 'John']

# Setting providing implicit data type 'object'
np_arr = np.array(object = mixed_list, dtype = object)
print(np_arr)

[list([2, 3, 1]) 'New York' 5.6 -10 'John']


In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]

multidim = np.array([list1, list2])
print(multidim)

[[1 2 3]
 [4 5 6]]


In [ ]:
list3 = [7,8,9]
list4 = [10,11,12]

multidim2 = np.array([list3, list4])

print([multidim],[multidim2])

[[array([[1, 2, 3],
       [4, 5, 6]])], [array([[ 7,  8,  9],
       [10, 11, 12]])]]


In [ ]:
list_3_dimensional = [[[1, 2, 3], [4, 5, 6]],
      [[7, 8, 9], [10, 11, 12]],
      [[13, 14, 15], [16, 17, 18]] , [[1, 2, 3], [4, 5, 6]],
      [[7, 8, 9], [10, 11, 12]],
      [[13, 14, 15], [16, 17, 18]]]

list2_3_dimensional = [[[1, 2, 3], [4, 5, 6]],
      [[7, 8, 9], [10, 11, 12]],
      [[13, 14, 15], [16, 17, 18]] , [[1, 2, 3], [4, 5, 6]],
      [[7, 8, 9], [10, 11, 12]],
      [[13, 14, 15], [16, 17, 18]]]

# Creating a 3_dimensional array from 'list_3_dimensional'
np_arr = np.array([list_3_dimensional, list2_3_dimensional])

print(np_arr)


[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]

  [[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]

  [[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]

  [[13 14 15]
   [16 17 18]]]]


In [ ]:
np_arr = np.array([[1, -1], [0, 1]])

# Getting the dimension in np_arr
num_of_dim = np_arr.ndim
print(num_of_dim)
print(np_arr)
print(np_arr.size)
print(np_arr.shape)

2
[[ 1 -1]
 [ 0  1]]
4
(2, 2)


In [ ]:
nparray = np.arange(30).reshape(5,2,3)
print(nparray)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]


In [ ]:
#slicing
print(nparray[:5:2, 0:2, 0:3:2])

[[[ 0  2]
  [ 3  5]]

 [[12 14]
  [15 17]]

 [[24 26]
  [27 29]]]


In [ ]:
import numpy as np
str_arr = np.array(object = [['apple', 'banana', 'cherry'],
                             ['date', 'fig', 'grape'],
                             ['kiwi', 'lemon', 'mango']])
print(str_arr)

[['apple' 'banana' 'cherry']
 ['date' 'fig' 'grape']
 ['kiwi' 'lemon' 'mango']]


In [ ]:
str_arr[1,1]

'fig'

In [ ]:

str_arr[1][1]

'fig'

In [ ]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# Accessing the last array of the last 2-dimensional array of 'arr'
last_2_dimensional = arr[1, 2]
print(last_2_dimensional)

[21 22 23 24]


In [ ]:
print(arr[1])

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(arr[1,2,0])

21


In [ ]:
print(arr[-2,-1,-3])

10


In [ ]:
import numpy as np
np_arr = np.array([[1, 2, 3], [4, 5, 6]])
condition = (np_arr > 2) | (np_arr < 5)

print(np_arr[(np_arr > 2) & (np_arr < 5)])

print(condition)

[3 4]
[[ True  True  True]
 [ True  True  True]]


In [ ]:
num_arr = np.array([23, 56, 87, 25, 64, 82, 64, 36, 87, 56, 98, 15, 25, 35, 76, 36, 67, 89, 35, 67, 64, 45, 37, 78])

count_elements = len(num_arr[num_arr > 50])

In [ ]:
print(count_elements)

14


In [ ]:
A = np.array([[[1, 2, 3], [4, 5, 6]],
     [[7, 8, 9], [10, 11, 12]]])

B = np.array([[[13, 14, 15], [16, 17, 18]],
     [[19, 20, 21], [22, 23, 24]]])

# Performing sum
sum_arr = A + B

sum_arr

array([[[14, 16, 18],
        [20, 22, 24]],

       [[26, 28, 30],
        [32, 34, 36]]])

In [ ]:
import numpy as np
np_arr = np.array([['Abhinav', 'Bhaskar', 'Manisha'],
                   ['EMP0046', 'EMP1218', 'EMP9453'],
                   [42, 34, 27]])

new = np.array([['Priya', 'EMP4251', 22], ['Rashid', 'EMP8576', 26]])

np_arr[:, 1:] = new.T.reshape(3,2)

print(np_arr)

[['Abhinav' 'Priya' 'Rashid']
 ['EMP0046' 'EMP4251' 'EMP8576']
 ['42' '22' '26']]


In [ ]:
import numpy as np
np_arr = np.array([['Abhinav', 'Bhaskar', 'Manisha'],
                   ['EMP0046', 'EMP1218', 'EMP9453'],
                   [42, 34, 27]])

new = np.array([['Priya', 'EMP4251', 22], ['Rashidi', 'EMP8576', 26]])

np_arr[:, 1:] = new.T
print(np_arr)

[['Abhinav' 'Priya' 'Rashidi']
 ['EMP0046' 'EMP4251' 'EMP8576']
 ['42' '22' '26']]


In [ ]:
import numpy as np
np_arr = np.array([['Abhinav', 'Bhaskar', 'Manisha'],
                   ['EMP0046', 'EMP1218', 'EMP9453'],
                   [42, 34, 27]])

new = np.array([['Priya', 'EMP4251', 22], ['Rashmi', 'EMP8576', 26]])

np_arr[:, 1:] = new.transpose()
print(np_arr)

[['Abhinav' 'Priya' 'Rashmi']
 ['EMP0046' 'EMP4251' 'EMP8576']
 ['42' '22' '26']]


In [ ]:
new = np.array([['Priya', 'EMP4251', 22], ['Rashmi', 'EMP8576', 26]])
print(new)


[['Priya' 'EMP4251' '22']
 ['Rashmi' 'EMP8576' '26']]


In [ ]:
print(new.T)

[['Priya' 'Rashmi']
 ['EMP4251' 'EMP8576']
 ['22' '26']]


In [ ]:
print(new.reshape(3,2))

[['Priya' 'EMP4251']
 ['22' 'Rashmi']
 ['EMP8576' '26']]


In [ ]:
check = np.array( [1.0, 2, 3.5, 0.2, True] )
print(check, check.ndim, check.dtype, check.size, check.shape)

[1.  2.  3.5 0.2 1. ] 1 float64 5 (5,)


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [ ]:
np_arr = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])
print(np_arr)
print(np_arr.reshape(-1))
print(np_arr)
print(np_arr.reshape(-9))

[[100 200 300]
 [400 500 600]
 [700 800 900]]
[100 200 300 400 500 600 700 800 900]
[[100 200 300]
 [400 500 600]
 [700 800 900]]
[100 200 300 400 500 600 700 800 900]


In [ ]:
np_arr = np.array([100, 200, 300])
print(np_arr)

[100 200 300]


In [ ]:
print(np_arr.reshape(-1,1))

[[100]
 [200]
 [300]]


In [ ]:
print(np_arr.reshape(1,-1))

[[100 200 300]]


In [ ]:
np_arr = np.array([[1, 5], [-5, 2], [3, 1]])
des_arr = np.array([[1, -5], [5, 2], [4, -6]])
print(np_arr)
print(des_arr)


[[ 1  5]
 [-5  2]
 [ 3  1]]
[[ 1 -5]
 [ 5  2]
 [ 4 -6]]


In [ ]:
print(np_arr.T.reshape(3,2))

[[ 1 -5]
 [ 3  5]
 [ 2  1]]


In [ ]:
change = np.delete(np_arr,2, axis=0)
change

array([[ 1,  5],
       [-5,  2]])

In [ ]:
change1 = np.append(change,[[4,-6]], axis=0)
print(change1)

[[ 1  5]
 [-5  2]
 [ 4 -6]]


In [ ]:
import numpy as np
fruits = np.array(['banana', 'cherry'])
fruits[fruits == 'cherry'] = 'grape'
print(fruits)

['banana' 'grape']


In [ ]:
fruits = np.array(['banana', 'cherry'])
fruits[1] = 'grape'
print(fruits)

['banana' 'grape']


In [ ]:
fruits.replace('cherry', 'grape')

AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [ ]:
point1 = np.array([-2, 3, 5])
point2 = np.array([1, 0, -4])
euc_dist = (point1 - point2)
euc_dist = 2* sum(euc_dist)
print(euc_dist)

18


In [ ]:
np.exp(np.array([1, 2, 3, 4, 5]))

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
np.array([np.exp(1), np.exp(2), np.exp(3), np.exp(4), np.exp(5)])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
np.e ** np.array([1, 2, 3, 4, 5])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:

np.exp([1, 2, 3, 4, 5])

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
np.linspace(-10, 10, 20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [ ]:
arr_1 = np.array([1, -2, 3, 4])
arr_2 = np.array([-4, 2, -4])
arr_3 = np.array([7, -2, -5, 6, 4])
concatenate_arr = np.concatenate((arr_1, arr_2, arr_3))
print(concatenate_arr)

[ 1 -2  3  4 -4  2 -4  7 -2 -5  6  4]


In [7]:
import numpy as np
input_list= [1,2,3,4,5,76,6,8,99,10]
m= 5
n=99

array_1 = np.array(input_list)
final_array = np.array([a for a in array_1 if  a>m and a<n])
print(final_array)

[76  6  8 10]


In [11]:
multiple5 = np.arange(5,5*11,5)
print(multiple5)

[ 5 10 15 20 25 30 35 40 45 50]


In [37]:
array1 = np.array([0])
array2 = np.array([1])
#n = int(input())
tile_array = np.tile([array1, array2], [2,2])
print(tile_array)

[[0 0]
 [1 1]
 [0 0]
 [1 1]]


In [9]:
import numpy as np

array1 = np.array([0, 1])
array2 = np.array([1, 0])
n = int(input("Enter the size of the checkerboard: "))

# Use np.tile to repeat the pattern for n rows and columns
tile_array = np.tile([array1, array2], (n,n))[:n,:n]
print(tile_array)


Enter the size of the checkerboard: 20
[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


In [13]:

import numpy as np

#data for student performance
modules_completed = np.array([12, 15, 18, 20, 14, 16, 22, 10, 13, 17, 19, 21, 14, 12, 16, 18, 20, 14, 16, 19])
quiz_scores = np.array([85, 90, 78, 92, 88, 76, 95, 80, 89, 94, 81, 87, 93, 79, 91, 84, 88, 75, 82, 96])

more_than15 = np.array(modules_completed[modules_completed > 15])
print(more_than15, np.size(more_than15))

[18 20 16 22 17 19 21 16 18 20 16 19] 12


In [14]:
print(np.sum(modules_completed>15))

12


In [15]:
print(np.mean(quiz_scores))

86.15


In [16]:
print(np.array(quiz_scores[quiz_scores>90]))

[92 95 94 93 91 96]


In [19]:
print(np.sum(quiz_scores>90))

6


In [20]:
correct_scores = np.array([82, 88, 76, 95, 90])
quiz_scores[:5] = correct_scores
print(quiz_scores)

[82 88 76 95 90 76 95 80 89 94 81 87 93 79 91 84 88 75 82 96]


In [23]:
import numpy as np

#data for student performance
modules_completed = np.array([12, 15, 18, 20, 14, 16, 22, 10, 13, 17, 19, 21, 14, 12, 16, 18, 20, 14, 16, 19])
quiz_scores = np.array([85, 90, 78, 92, 88, 76, 95, 80, 89, 94, 81, 87, 93, 79, 91, 84, 88, 75, 82, 96])

percent_below80 = np.sum(quiz_scores<80) / len(quiz_scores) * 100
print(percent_below80)

20.0
